### ISSUE TITLE
Consider clarifying what “blazingly fast” means

### ISSUE THREAD

**Issue by matklad** [gleam-lang/website#119]
At the moment, the website says:

> so all Gleam programs are as blazingly fast as their Erlang counterpart.

This reads to me as a rather misleading claim. On the first reading of that whole paragraph, l thought “this is all completely wrong”, on a second, more careful reading, I though “OK, technically this is all correct, but you need to have a deep knowledge of beam to understand what’s claimed exactly”.

The problem here is that, when people speak about unqualified performance, they usually have in mind CPU efficiency. Erlang is generally as blazingly fast as Python, which is to say, not really fast at all.

While Erlang wouldn’t be the speed champ at Fibonacci calculations or [3D rendering](https://github.com/dgud/wings), it does have two performance super-powers:

* concurrency is very cheap, as Erlang process utilizes very few resources
* VM is optimized for latency (per-process heap with no global stop the world, pre-emptive scheduling with tight budgeting of reductions)

So, I suggest to more clearly express what gleam performance is and is not about, such that one can’t misunderstand the claim even if one doesn’t have pre-existing Erlang knowledge. So, something along the lines of:

> While Erlang’s virtual machine, BEAM, isn’t particularly efficient for CPU-bound computations, it excels for building highly concurrent, low-latency network applications and web servers, as exemplified by …..

**Comment by lpil** [comment]
> “OK, technically this is all correct, but you need to have a deep knowledge of beam to understand what’s claimed exactly”.

This is going to be case for all technologies. It is common for projects to claim they are fast without qualification, while here we have explicitly said we are as fast as Erlang, making it easier to research the performance characteristics here.

> Erlang is generally as blazingly fast as Python, which is to say, not really fast at all.

I think you're underselling the VM's CPU bound performance here.

In my previous tests the BEAM would happily beat Python and the JVM for CPU bound single threaded workloads that use persistent immutable data structures and do not involve numerical computation. Jason (a native Elixir JSON encoder/decoder) can match the performance of Jiffy, a JSON encoder/decoder written in C.

Given Erlang has a JIT since the last release this has likely improved further, with up to a 40% improvement of CPU bound workloads being reported in some cases.

> I suggest to more clearly express what gleam performance is 

Documentation on the performance characteristics of the BEAM that references the Erlang efficiency guide sounds like a great idea. We would likely also want one for when targeting JavaScript using V8, and for targeting native code via Lumen when that is available.

**Comment by matklad** [comment]
This all makes sense! I guess we are at the “reasonable people can disagree” level here.

I’ll respond to specific points, but please read this as a feedback from one reader, rather than an attempt to strongly argue for a specific point :)

> while here we have explicitly said we are as fast as Erlang

The phrasing also implies that Erlang is blazingly fast. “blazingly fast as Erlang” to my ear sounds more or less like “blazingly fast as Python” or “memory safe as C”. This might be due to my misunderstanding of BEAM perf though!

> I think you're underselling the VM's CPU bound performance here.

Maybe! At this point, I still believe in “Python’s ballpark” estimate though, based on two reasons:

* Erlang is a highly dynamic language/runtime, so it should behave roughly as Python/Ruby. It’s highly probably that it’s slower than JavaScript/v8, as that is *best case* for this class of runtimes.
* https://benchmarksgame-team.pages.debian.net/benchmarksgame/which-programs-are-fastest.html places Erlang (otp 24, so with jit) between PHP and Python. Although I don’t think this site is great for comparing two specific languages, I think it does reliably split languages into “performance classes”. Erlang looks like it belongs with slowest languages.

I am not particularly convinced with your specific examples. 

The “immutable data structures” benchmarks sounds that it *might* actually measure “part of runtime implemented in C” rather than overall language perf. That is, at least some Erlang collections are implemented in C, while Python/Scala immutable collections are implemented in the languages themselves. A similar case would be measuring bigint arithmetics perf between Java and Python. Python would be faster, as it has a particularly well optimized (in C) bigint implementation.

Jason/Jiffy probably demonstrates a related effect. JSON encoding/decoding from/to high-level language data-structures is often bottlencked not on JSON parsing per se, but on creating/traversing objects in the heap. So, switch to C doesn’t make it universally faster, and might actually incure penalties for crossing managed/native boundary.

> Jason (a native Elixir JSON encoder/decoder) can match or best the performance of Jiffy, a JSON encoder/decoder written in C.

To me, this specific phrasing actually gives the same feeling as the original paragraph from the website. It is pedantically correct, but paints the wrong picture. The phrasing from Jason’s own readme seems much more reasonable to me:

> The performance is comparable to jiffy, which is implemented in C as a NIF. Jason is usually only twice as slow.


Again, to re-iterate, this is just a feedback from someone reading the landing page, don’t feel pressured to react to this, it might be that I am just an overly nitpicky reader :)

**Comment by lpil** [comment]
> https://benchmarksgame-team.pages.debian.net/benchmarksgame/which-programs-are-fastest.html places Erlang (otp 24, so with jit) between PHP and Python. Although I don’t think this site is great for comparing two specific languages, I think it does reliably split languages into “performance classes”. Erlang looks like it belongs with slowest languages.

I've investigated this one before! The Erlang entries I read were very poorly written. I wouldn't put much weight into that particular benchmark contest as there is no guarentee that the entries are optimal, just that they technically do the thing they claim to do. For example, one of them would spawn a process instead of calling a function when they wanted to perform recusion, which is much slower. I guess the author assumed that writing in Erlang means you have to use actors.

> Again, to re-iterate, this is just a feedback from someone reading the landing page, don’t feel pressured to react to this, it might be that I am just an overly nitpicky reader :)

Not at all! The website copy was rather quickly thrown together and is a tiny project trying to market itself mostly. I expect this will change a lot soon as we need to rework it to take into account the fact Gleam targets JavaScript as well as Erlang now.
